title: Bacchus
description: 서울대학교 컴퓨터공학부 관리자 그룹
url: "https://bacchus.snucse.org"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year-:month-:day-:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - flake.nix
  - flake.lock
  - README.md
